export const pharmacologyGITMCQs = [
  {
    question: "A patient takes magnesium hydroxide as an antacid and develops loose stools, whereas aluminium hydroxide tends to do the opposite. Which statement best describes their bowel effects?",
    case_study: "",
    option_a: "Magnesium antacids cause diarrhoea; aluminium antacids cause constipation",
    option_b: "Magnesium antacids cause constipation; aluminium antacids cause diarrhoea",
    option_c: "Both cause severe diarrhoea",
    option_d: "Both cause constipation",
    option_e: "Neither affects the bowel",
    correct_answer: "A",
    explanation_a: "Magnesium-containing antacids tend to cause diarrhoea, while aluminium-containing antacids tend to cause constipation; combination products balance the two.",
    explanation_b: "This reverses the two effects.",
    explanation_c: "Aluminium antacids constipate rather than cause diarrhoea.",
    explanation_d: "Magnesium antacids loosen rather than constipate.",
    explanation_e: "Both clearly affect bowel habit.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (Antacids); Lippincott Pharmacology (Antacid Therapy); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Mg = Must Go (diarrhoea); Al = constipation. Antacids can also bind and reduce absorption of other drugs (e.g. tetracyclines, iron, fluoroquinolones).",
  },
  {
    question: "A patient with a peptic ulcer is given sucralfate. Unlike acid-lowering drugs, sucralfate heals the ulcer by:",
    case_study: "",
    option_a: "Blocking the proton pump",
    option_b: "Forming a protective physical coating over the ulcer base (activated by acid)",
    option_c: "Neutralising stomach acid",
    option_d: "Blocking histamine H2 receptors",
    option_e: "Killing Helicobacter pylori",
    correct_answer: "B",
    explanation_a: "It does not block the proton pump.",
    explanation_b: "In the acidic stomach, sucralfate polymerises into a sticky gel that binds to the ulcer base, forming a physical protective barrier against acid and pepsin while the ulcer heals.",
    explanation_c: "It is not an acid neutraliser (antacid).",
    explanation_d: "It does not block H2 receptors.",
    explanation_e: "It has no significant antibacterial action against H. pylori.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung (Mucosal Protective Agents); Lippincott Pharmacology (Sucralfate); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Sucralfate forms a protective coating over the ulcer base (cytoprotective). Because sucralfate needs acid to activate, it should not be given at the same time as antacids or strong acid suppressants. Sucralfate can reduce absorption of other drugs and may cause constipation (aluminium content).",
  },
  {
    question: "A patient has taken a proton pump inhibitor daily for many years. Long-term PPI use is associated with which of the following?",
    case_study: "",
    option_a: "High magnesium and high calcium",
    option_b: "Iron overload",
    option_c: "Hypomagnesaemia, vitamin B12 deficiency and increased Clostridioides difficile risk",
    option_d: "Improved bone density",
    option_e: "Hyperkalaemia",
    correct_answer: "C",
    explanation_a: "PPIs tend to LOWER magnesium, not raise it.",
    explanation_b: "Reduced acid impairs iron absorption (a risk of deficiency), not iron overload.",
    explanation_c: "Long-term acid suppression with PPIs is linked to hypomagnesaemia, vitamin B12 deficiency (acid is needed to release B12 from food), increased risk of enteric infections including C. difficile, and an increased fracture risk.",
    explanation_d: "Long-term PPIs are associated with reduced bone density/fractures, not improvement.",
    explanation_e: "Hyperkalaemia is not a characteristic PPI effect.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (PPI Adverse Effects); Lippincott Pharmacology (Long-Term PPIs); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Long-term PPIs → low magnesium, low B12, more C. difficile, fracture risk. Use the lowest effective PPI dose for the shortest necessary time, and review long-term use. Reduced gastric acid underlies most long-term PPI adverse effects (impaired absorption and host defence).",
  },
  {
    question: "Ranitidine reduces gastric acid secretion by:",
    case_study: "",
    option_a: "Inhibiting the proton pump",
    option_b: "Neutralising acid chemically",
    option_c: "Coating the stomach lining",
    option_d: "Blocking histamine H2 receptors on parietal cells",
    option_e: "Blocking muscarinic receptors",
    correct_answer: "D",
    explanation_a: "Proton pump inhibition describes omeprazole.",
    explanation_b: "Chemical neutralisation describes antacids.",
    explanation_c: "Coating the lining describes sucralfate.",
    explanation_d: "Ranitidine competitively blocks histamine H2 receptors on gastric parietal cells, reducing histamine-stimulated acid secretion.",
    explanation_e: "Muscarinic blockade is not the H2-antagonist mechanism.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (H2 Antagonists); Lippincott Pharmacology (Ranitidine); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Ranitidine blocks parietal-cell H2 receptors → less acid. H2 blockers are less potent acid suppressants than PPIs but act faster and are useful for nocturnal acid. Histamine, gastrin and acetylcholine all stimulate parietal-cell acid secretion; the proton pump is the final common step.",
  },
  {
    question: "A patient's Helicobacter pylori has failed standard triple therapy, so a bismuth-containing 'quadruple' regimen is used. Apart from antibiotics and a proton pump inhibitor, the added agent is:",
    case_study: "",
    option_a: "An antacid",
    option_b: "A bulk-forming laxative",
    option_c: "An antiemetic",
    option_d: "A stimulant laxative",
    option_e: "Bismuth (mucosa-protective and toxic to H. pylori)",
    correct_answer: "E",
    explanation_a: "An antacid is not the key component of quadruple therapy.",
    explanation_b: "A bulk-forming laxative has no role here.",
    explanation_c: "An antiemetic is not part of eradication therapy.",
    explanation_d: "A stimulant laxative has no role here.",
    explanation_e: "Bismuth compounds are added in quadruple therapy for resistant H. pylori; bismuth coats and protects the mucosa and has direct toxicity against the organism.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (H. pylori Therapy); Lippincott Pharmacology (Bismuth); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Bismuth is the added agent in quadruple therapy for resistant H. pylori. Bismuth characteristically blackens the stool and tongue, which is harmless but should be explained to the patient. Quadruple therapy is typically a PPI + bismuth + two antibiotics (e.g. tetracycline + metronidazole).",
  },
  {
    question: "A patient with Parkinson's disease needs an antiemetic that will not worsen his movement disorder. Domperidone is chosen because, unlike metoclopramide, it:",
    case_study: "",
    option_a: "Does not readily cross the blood–brain barrier (so causes few extrapyramidal effects)",
    option_b: "Blocks 5-HT3 receptors",
    option_c: "Is a proton pump inhibitor",
    option_d: "Stimulates dopamine receptors centrally",
    option_e: "Is an antihistamine",
    correct_answer: "A",
    explanation_a: "Domperidone is a peripheral dopamine (D2) antagonist that poorly crosses the blood–brain barrier, so it provides prokinetic/antiemetic effects with minimal extrapyramidal reactions – useful in Parkinson's disease.",
    explanation_b: "It is a dopamine antagonist, not a 5-HT3 blocker.",
    explanation_c: "It is not a proton pump inhibitor.",
    explanation_d: "It blocks, not stimulates, dopamine receptors.",
    explanation_e: "It is not an antihistamine.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Prokinetics); Lippincott Pharmacology (Domperidone); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Domperidone is a peripheral D2 antagonist with few central (extrapyramidal) effects. Metoclopramide crosses the BBB and can cause extrapyramidal reactions; domperidone largely does not. Domperidone can prolong the QT interval, so caution is needed with other QT-prolonging drugs.",
  },
  {
    question: "A patient with chronic liver disease becomes confused and drowsy (hepatic encephalopathy). He is started on lactulose, which helps mainly by:",
    case_study: "",
    option_a: "Neutralising stomach acid",
    option_b: "Reducing absorption of ammonia from the gut (acidifying the colon and acting as an osmotic laxative)",
    option_c: "Killing gut bacteria directly as an antibiotic",
    option_d: "Blocking the proton pump",
    option_e: "Increasing ammonia production",
    correct_answer: "B",
    explanation_a: "It does not neutralise stomach acid.",
    explanation_b: "Colonic bacteria ferment lactulose to acids, which acidify the colon and trap ammonia as non-absorbable ammonium; as an osmotic laxative it also speeds removal of nitrogenous waste – lowering blood ammonia in hepatic encephalopathy.",
    explanation_c: "It is not an antibiotic (though rifaximin is used alongside it to reduce ammonia-producing bacteria).",
    explanation_d: "It does not block the proton pump.",
    explanation_e: "It REDUCES, not increases, ammonia absorption.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Laxatives/Hepatic Encephalopathy); Lippincott Pharmacology (Lactulose); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Lactulose lowers blood ammonia (acidifies colon, traps ammonia, osmotic laxative). Lactulose is titrated to produce 2–3 soft stools per day in hepatic encephalopathy. Lactulose is also a standard osmotic laxative for simple constipation.",
  },
  {
    question: "An elderly patient with constipation is given senna. Senna relieves constipation by:",
    case_study: "",
    option_a: "Adding bulk to the stool",
    option_b: "Drawing water into the bowel osmotically",
    option_c: "Stimulating colonic peristalsis (a stimulant laxative)",
    option_d: "Softening the stool by a detergent action",
    option_e: "Lubricating the bowel wall",
    correct_answer: "C",
    explanation_a: "Adding bulk describes bulk-forming laxatives (ispaghula).",
    explanation_b: "Drawing water in osmotically describes lactulose/macrogol.",
    explanation_c: "Senna is a stimulant laxative; it stimulates the colonic myenteric plexus to increase peristalsis, promoting defecation.",
    explanation_d: "A detergent stool-softening action describes docusate.",
    explanation_e: "Lubrication describes liquid paraffin.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (Laxatives); Lippincott Pharmacology (Stimulant Laxatives); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Senna = stimulant laxative (increases colonic peristalsis). Prolonged stimulant-laxative use can cause electrolyte loss and dependence. Laxative classes: bulk-forming, osmotic, stimulant, stool-softener and lubricant.",
  },
  {
    question: "A patient with mild constipation is advised to take ispaghula husk (a bulk-forming laxative) with plenty of water. Bulk-forming laxatives work by:",
    case_study: "",
    option_a: "Stimulating colonic nerves directly",
    option_b: "Drawing in water by osmosis from non-absorbable sugars",
    option_c: "Killing gut bacteria",
    option_d: "Absorbing water to increase faecal bulk (which stimulates peristalsis)",
    option_e: "Inhibiting gut motility",
    correct_answer: "D",
    explanation_a: "Direct nerve stimulation describes stimulant laxatives.",
    explanation_b: "Osmotic water-drawing describes lactulose/macrogol.",
    explanation_c: "They do not kill gut bacteria.",
    explanation_d: "Bulk-forming laxatives are indigestible fibre that absorb water and swell, increasing faecal mass; the larger, softer stool stimulates peristalsis.",
    explanation_e: "They promote, not inhibit, bowel movement.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Bulk Laxatives); Lippincott Pharmacology (Fibre); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Bulk-forming laxatives increase faecal bulk and water content. Bulk-forming laxatives must be taken with adequate fluid to avoid bowel obstruction. Fibre/bulk laxatives are first-line for simple chronic constipation.",
  },
  {
    question: "A patient with non-infective watery diarrhoea is given loperamide for symptom relief. Loperamide reduces diarrhoea by:",
    case_study: "",
    option_a: "Killing gut bacteria",
    option_b: "Drawing water into the bowel",
    option_c: "Stimulating peristalsis",
    option_d: "Replacing fluids and electrolytes",
    option_e: "Acting as an opioid agonist on the gut to slow motility (it does not cross the blood–brain barrier)",
    correct_answer: "E",
    explanation_a: "It is not an antibiotic.",
    explanation_b: "It does not draw water into the bowel.",
    explanation_c: "It SLOWS, not stimulates, peristalsis.",
    explanation_d: "Fluid/electrolyte replacement is the role of oral rehydration solution.",
    explanation_e: "Loperamide is an opioid (µ-receptor) agonist that acts on the gut wall to slow intestinal motility and increase water absorption; because it does not cross the blood–brain barrier, it lacks central opioid effects.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Antidiarrhoeals); Lippincott Pharmacology (Loperamide); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loperamide is a gut-selective opioid that slows motility (no central effects). Avoid loperamide in invasive/inflammatory diarrhoea (e.g. dysentery, C. difficile), where slowing transit can worsen the illness. Diphenoxylate (combined with atropine) is a related opioid antidiarrhoeal.",
  },
  {
    question: "A child in a Pakistani village has acute watery diarrhoea with mild dehydration. The cornerstone of treatment is oral rehydration solution (ORS), which is effective because glucose enhances:",
    case_study: "",
    option_a: "Intestinal sodium and water absorption via the sodium-glucose cotransporter",
    option_b: "Vomiting",
    option_c: "Gut motility",
    option_d: "Gastric acid secretion",
    option_e: "Ammonia absorption",
    correct_answer: "A",
    explanation_a: "ORS works because the sodium-glucose cotransporter (SGLT1) keeps absorbing sodium (and water with it) even during secretory diarrhoea, so adding glucose drives rehydration.",
    explanation_b: "ORS treats, rather than causes, vomiting-related fluid loss.",
    explanation_c: "It does not act by changing gut motility.",
    explanation_d: "It does not work via gastric acid.",
    explanation_e: "It has nothing to do with ammonia absorption.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (Oral Rehydration); Lippincott Pharmacology (Fluid Therapy); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "ORS uses sodium-glucose cotransport to absorb sodium and water. Glucose-coupled sodium absorption is preserved in cholera, which is why ORS is life-saving even in severe secretory diarrhoea. ORS plus continued feeding (and zinc in children) is the mainstay of diarrhoea management.",
  },
  {
    question: "A patient with mild ulcerative colitis is maintained on mesalazine (5-aminosalicylic acid). Aminosalicylates act mainly by:",
    case_study: "",
    option_a: "Killing colonic bacteria",
    option_b: "Delivering local anti-inflammatory 5-ASA to the bowel mucosa",
    option_c: "Blocking the proton pump",
    option_d: "Slowing gut motility",
    option_e: "Stimulating peristalsis",
    correct_answer: "B",
    explanation_a: "They are not primarily antibacterial.",
    explanation_b: "Aminosalicylates deliver 5-ASA locally to the inflamed colonic mucosa, where it has a topical anti-inflammatory action (reducing prostaglandins/leukotrienes and scavenging free radicals).",
    explanation_c: "They do not block the proton pump.",
    explanation_d: "They do not slow gut motility.",
    explanation_e: "They do not stimulate peristalsis.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (IBD Drugs); Lippincott Pharmacology (Aminosalicylates); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Mesalazine (5-ASA) gives a local anti-inflammatory effect in ulcerative colitis. Sulfasalazine is 5-ASA linked to a sulfapyridine carrier; the sulfa component causes many of its side effects (e.g. rash, reversible infertility in men). Aminosalicylates are first-line for inducing and maintaining remission in mild-to-moderate ulcerative colitis.",
  },
  {
    question: "A patient with severe Crohn's disease that has not responded to corticosteroids and immunosuppressants is given infliximab. Infliximab works by:",
    case_study: "",
    option_a: "Inhibiting calcineurin",
    option_b: "Inhibiting dihydrofolate reductase",
    option_c: "Blocking tumour necrosis factor-alpha (an anti-TNF monoclonal antibody)",
    option_d: "Blocking histamine receptors",
    option_e: "Inhibiting the proton pump",
    correct_answer: "C",
    explanation_a: "Calcineurin inhibition describes ciclosporin/tacrolimus.",
    explanation_b: "Dihydrofolate reductase inhibition describes methotrexate.",
    explanation_c: "Infliximab is a monoclonal antibody against tumour necrosis factor-alpha (TNF-α), a key inflammatory cytokine; blocking it controls moderate-to-severe inflammatory bowel disease.",
    explanation_d: "It does not block histamine receptors.",
    explanation_e: "It does not inhibit the proton pump.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung (Biologic Therapies); Lippincott Pharmacology (Anti-TNF Agents); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Infliximab is an anti-TNF-α monoclonal antibody for refractory IBD. Before starting anti-TNF therapy, screen for latent tuberculosis, because it can reactivate TB. Anti-TNF biologics increase the risk of serious and opportunistic infections.",
  },
  {
    question: "A pregnant woman has troublesome nausea and vomiting, and a separate patient has motion sickness. Both can be treated with an antiemetic from which class, often chosen for its safety and antihistamine action?",
    case_study: "",
    option_a: "A 5-HT3 antagonist",
    option_b: "A proton pump inhibitor",
    option_c: "A stimulant laxative",
    option_d: "An H1 antihistamine (e.g. cyclizine or promethazine)",
    option_e: "An anti-TNF biologic",
    correct_answer: "D",
    explanation_a: "5-HT3 antagonists are mainly for chemotherapy/postoperative nausea, not first-line for motion sickness.",
    explanation_b: "Proton pump inhibitors are not antiemetics.",
    explanation_c: "Stimulant laxatives have no antiemetic role.",
    explanation_d: "H1 antihistamines such as cyclizine and promethazine are effective for motion sickness and for nausea in pregnancy, where they have a long record of safety.",
    explanation_e: "Anti-TNF biologics are for inflammatory disease, not nausea.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Antiemetics); Lippincott Pharmacology (Antihistamine Antiemetics); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "H1 antihistamines (cyclizine, promethazine) treat motion sickness and pregnancy nausea. Antihistamine antiemetics commonly cause drowsiness through their central H1 effect. Match the antiemetic to the cause – vestibular/motion (antihistamines, antimuscarinics) vs chemotherapy (5-HT3 antagonists).",
  },
  {
    question: "A diabetic patient with gastroparesis (delayed gastric emptying) is given the antibiotic erythromycin, which is being used here as a prokinetic. It promotes gastric emptying by:",
    case_study: "",
    option_a: "Blocking dopamine receptors",
    option_b: "Blocking 5-HT3 receptors",
    option_c: "Inhibiting acetylcholinesterase",
    option_d: "Stimulating opioid receptors",
    option_e: "Acting as a motilin receptor agonist",
    correct_answer: "E",
    explanation_a: "Dopamine-receptor blockade describes metoclopramide/domperidone, a different prokinetic mechanism.",
    explanation_b: "It does not block 5-HT3 receptors.",
    explanation_c: "It does not inhibit acetylcholinesterase.",
    explanation_d: "It does not stimulate opioid receptors.",
    explanation_e: "Beyond its antibacterial action, erythromycin acts as a motilin receptor agonist on gut smooth muscle, strongly stimulating gastric emptying – useful in gastroparesis.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung (Prokinetics); Lippincott Pharmacology (Motilin Agonists); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Erythromycin is a motilin receptor agonist (prokinetic). Erythromycin's prokinetic effect tends to wane with continued use (tachyphylaxis), limiting long-term use. Erythromycin is also used before endoscopy in upper-GI bleeding to clear the stomach of blood.",
  },
  {
    question: "A patient with small cholesterol gallstones, who is unfit for surgery, is treated with ursodeoxycholic acid. It works by:",
    case_study: "",
    option_a: "Reducing biliary cholesterol, helping to dissolve cholesterol gallstones",
    option_b: "Contracting the gallbladder forcefully",
    option_c: "Blocking bile production completely",
    option_d: "Neutralising stomach acid",
    option_e: "Killing gut bacteria",
    correct_answer: "A",
    explanation_a: "Ursodeoxycholic acid reduces the cholesterol content of bile, making it less saturated, which can gradually dissolve small radiolucent (cholesterol) gallstones.",
    explanation_b: "It does not act by forcefully contracting the gallbladder.",
    explanation_c: "It does not block bile production.",
    explanation_d: "It is not an antacid.",
    explanation_e: "It is not an antibacterial.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (Bile Acid Therapy); Lippincott Pharmacology (Ursodeoxycholic Acid); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Ursodeoxycholic acid reduces biliary cholesterol → dissolves cholesterol gallstones. It works only for small, non-calcified cholesterol stones with a functioning gallbladder, and takes months. Ursodeoxycholic acid is also used to treat primary biliary cholangitis.",
  },
  {
    question: "A patient with irritable bowel syndrome has crampy abdominal pain and is given hyoscine butylbromide (an antispasmodic). It relieves the cramps by:",
    case_study: "",
    option_a: "Stimulating gut contractions",
    option_b: "Blocking muscarinic receptors to relax gut smooth muscle",
    option_c: "Blocking the proton pump",
    option_d: "Increasing gut secretions",
    option_e: "Adding bulk to the stool",
    correct_answer: "B",
    explanation_a: "It relaxes, rather than stimulates, gut contractions.",
    explanation_b: "Hyoscine butylbromide is an antimuscarinic (anticholinergic) antispasmodic; blocking muscarinic receptors relaxes gastrointestinal smooth muscle and relieves colicky cramps.",
    explanation_c: "It does not block the proton pump.",
    explanation_d: "It reduces, rather than increases, secretions.",
    explanation_e: "It does not add bulk to the stool.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung (Antispasmodics); Lippincott Pharmacology (Antimuscarinics); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Hyoscine butylbromide is an antimuscarinic antispasmodic for gut colic/IBS. Antimuscarinic antispasmodics can cause dry mouth, blurred vision and urinary retention. Mebeverine is an alternative antispasmodic that acts directly on smooth muscle.",
  },
  {
    question: "A patient with chronic pancreatitis has greasy, foul-smelling, floating stools (steatorrhoea) and weight loss. He is started on pancreatic enzyme replacement (pancreatin) to:",
    case_study: "",
    option_a: "Reduce stomach acid",
    option_b: "Slow gut motility",
    option_c: "Replace deficient digestive enzymes (lipase, amylase, protease)",
    option_d: "Kill gut bacteria",
    option_e: "Stimulate the pancreas to secrete more enzymes",
    correct_answer: "C",
    explanation_a: "It is not an acid suppressant (though PPIs may be added to protect the enzymes).",
    explanation_b: "It does not slow gut motility.",
    explanation_c: "Exocrine pancreatic insufficiency causes malabsorption and steatorrhoea; pancreatin supplies the missing lipase, amylase and protease so fat and nutrients can be digested and absorbed.",
    explanation_d: "It is not an antibacterial.",
    explanation_e: "It replaces enzymes rather than stimulating the damaged pancreas.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Pancreatic Enzymes); Lippincott Pharmacology (Pancreatin); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Pancreatin replaces deficient digestive enzymes in pancreatic insufficiency. Pancreatic enzymes are acid-labile, so enteric-coated preparations (sometimes with a PPI) improve their effectiveness. Pancreatic enzyme replacement is also essential in cystic fibrosis with pancreatic insufficiency.",
  },
  {
    question: "A patient on clopidogrel after a coronary stent is also taking omeprazole. There is concern that omeprazole may reduce clopidogrel's effectiveness because omeprazole:",
    case_study: "",
    option_a: "Increases clopidogrel excretion",
    option_b: "Binds clopidogrel in the gut",
    option_c: "Induces clopidogrel metabolism",
    option_d: "Inhibits CYP2C19, the enzyme that activates clopidogrel (a prodrug)",
    option_e: "Blocks platelet ADP receptors itself",
    correct_answer: "D",
    explanation_a: "The interaction is via reduced activation, not increased excretion.",
    explanation_b: "It does not bind clopidogrel in the gut.",
    explanation_c: "It inhibits, not induces, the relevant enzyme.",
    explanation_d: "Clopidogrel is a prodrug that must be activated by CYP2C19; omeprazole inhibits CYP2C19, which can reduce formation of the active metabolite and blunt clopidogrel's antiplatelet effect.",
    explanation_e: "Omeprazole itself has no antiplatelet (ADP-blocking) action.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung (Drug Interactions); Lippincott Pharmacology (Clopidogrel–PPI Interaction); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Omeprazole inhibits CYP2C19, potentially reducing activation of clopidogrel. Pantoprazole inhibits CYP2C19 less, so it is often preferred when a PPI is needed with clopidogrel. Clopidogrel is an inactive prodrug requiring hepatic conversion to its active form.",
  },
  {
    question: "A patient with liver cirrhosis presents with massive vomiting of blood from bleeding oesophageal varices. Alongside urgent endoscopy, a drug is given to reduce portal/splanchnic blood flow and help control the bleeding, namely:",
    case_study: "",
    option_a: "Omeprazole",
    option_b: "Loperamide",
    option_c: "Lactulose",
    option_d: "Metoclopramide",
    option_e: "Octreotide (a somatostatin analogue)",
    correct_answer: "E",
    explanation_a: "Omeprazole reduces acid (useful in peptic ulcer bleeding) but does not lower portal pressure.",
    explanation_b: "Loperamide is an antidiarrhoeal with no role here.",
    explanation_c: "Lactulose treats encephalopathy but does not stop variceal bleeding.",
    explanation_d: "Metoclopramide is an antiemetic, not a treatment for variceal bleeding.",
    explanation_e: "Octreotide (a somatostatin analogue) reduces splanchnic and portal blood flow, lowering variceal pressure and helping to control acute variceal bleeding while definitive endoscopic treatment is arranged.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung (Somatostatin Analogues); Lippincott Pharmacology (Octreotide); Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Octreotide reduces splanchnic blood flow to help control variceal bleeding. Terlipressin (a vasopressin analogue) is an alternative agent used to reduce portal pressure in variceal bleeding. Acute variceal bleeding is managed with resuscitation, a vasoactive drug (octreotide/terlipressin), endoscopic band ligation and prophylactic antibiotics.",
  },
];
