export const pharmacologyRenalMCQs = [
  {
    question: "Acetazolamide produces a mild diuresis by inhibiting the enzyme carbonic anhydrase, mainly in the proximal convoluted tubule. This leads to increased urinary loss of:",
    case_study: "",
    option_a: "Bicarbonate (NaHCO₃)",
    option_b: "Only potassium",
    option_c: "Glucose",
    option_d: "Calcium only",
    option_e: "Uric acid only",
    correct_answer: "A",
    explanation_a: "Blocking carbonic anhydrase prevents bicarbonate reabsorption, so bicarbonate (with Na⁺ and water) is lost in the urine.",
    explanation_b: "Potassium loss can occur secondarily, but the primary effect is bicarbonate loss.",
    explanation_c: "Glucose loss is the effect of SGLT2 inhibitors, not acetazolamide.",
    explanation_d: "Calcium is not the primary ion lost with acetazolamide.",
    explanation_e: "Uric acid is not the primary substance lost.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Diuretics); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Carbonic anhydrase inhibitor → bicarbonate diuresis → metabolic acidosis. The effect is self-limiting. It also reduces aqueous humour and CSF production.",
  },
  {
    question: "Besides its diuretic effect, acetazolamide is clinically useful in the treatment of:",
    case_study: "",
    option_a: "Bacterial pneumonia",
    option_b: "Glaucoma and altitude (mountain) sickness",
    option_c: "Iron-deficiency anaemia",
    option_d: "Hypertension as first-line",
    option_e: "Diabetes mellitus",
    correct_answer: "B",
    explanation_a: "It is not an antibiotic for pneumonia.",
    explanation_b: "Acetazolamide lowers intraocular pressure in glaucoma and aids acclimatisation in altitude sickness.",
    explanation_c: "It does not treat iron-deficiency anaemia.",
    explanation_d: "It is not a first-line antihypertensive.",
    explanation_e: "It does not treat diabetes.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Carbonic Anhydrase Inhibitors); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Acetazolamide is used in glaucoma and altitude (mountain) sickness. In altitude sickness the induced metabolic acidosis stimulates ventilation. It reduces aqueous humour formation, lowering intraocular pressure.",
  },
  {
    question: "Mannitol is an osmotic diuretic. It works by:",
    case_study: "",
    option_a: "Blocking the Na-K-2Cl cotransporter",
    option_b: "Inhibiting aldosterone",
    option_c: "Remaining in the tubule and osmotically holding water there, promoting water excretion",
    option_d: "Blocking carbonic anhydrase",
    option_e: "Blocking the epithelial sodium channel",
    correct_answer: "C",
    explanation_a: "Blocking Na-K-2Cl is the mechanism of loop diuretics.",
    explanation_b: "Inhibiting aldosterone is the mechanism of spironolactone.",
    explanation_c: "Mannitol is filtered but not reabsorbed, so it osmotically holds water in the tubule, promoting water excretion.",
    explanation_d: "Blocking carbonic anhydrase is the mechanism of acetazolamide.",
    explanation_e: "Blocking ENaC is the mechanism of amiloride.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Osmotic Diuretics); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Mannitol osmotically holds water in the tubule. Given IV, it also draws water from tissues into the blood, reducing intracranial and intraocular pressure. It is used for raised intracranial pressure and acute glaucoma.",
  },
  {
    question: "Because mannitol first expands the intravascular (plasma) volume before diuresis occurs, it is CONTRAINDICATED in a patient with:",
    case_study: "",
    option_a: "Raised intracranial pressure",
    option_b: "Acute glaucoma",
    option_c: "A healthy young adult",
    option_d: "Congestive heart failure / pulmonary oedema",
    option_e: "Mild dehydration",
    correct_answer: "D",
    explanation_a: "Raised intracranial pressure is an indication for mannitol, not a contraindication.",
    explanation_b: "Acute glaucoma is an indication, not a contraindication.",
    explanation_c: "A healthy young adult is not the contraindicated group.",
    explanation_d: "The initial volume expansion can precipitate or worsen heart failure and pulmonary oedema, so mannitol is contraindicated there.",
    explanation_e: "Mild dehydration is not the classic contraindication highlighted here.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Mannitol Cautions); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Mannitol expands plasma volume first → avoid in heart failure/pulmonary oedema. It is also contraindicated in anuria, where it cannot be excreted and accumulates.",
  },
  {
    question: "Furosemide, the most powerful class of diuretic, produces its effect by inhibiting the Na⁺-K⁺-2Cl⁻ cotransporter in which part of the nephron?",
    case_study: "",
    option_a: "The proximal convoluted tubule",
    option_b: "The distal convoluted tubule",
    option_c: "The collecting duct",
    option_d: "The glomerulus",
    option_e: "The thick ascending limb of the loop of Henle",
    correct_answer: "E",
    explanation_a: "The proximal tubule is the site of acetazolamide's action.",
    explanation_b: "The distal convoluted tubule is the site of thiazide action.",
    explanation_c: "The collecting duct is the site of potassium-sparing diuretics.",
    explanation_d: "The glomerulus filters blood but is not the cotransporter site.",
    explanation_e: "Furosemide inhibits the Na⁺-K⁺-2Cl⁻ cotransporter in the thick ascending limb.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Loop Diuretics); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loop diuretics act on the thick ascending limb via the Na-K-2Cl (NKCC2) cotransporter. They abolish the medullary concentration gradient, impairing urine concentration. They also increase calcium and magnesium excretion.",
  },
  {
    question: "Which class of diuretic is the most potent and is the treatment of choice for the rapid relief of acute pulmonary oedema?",
    case_study: "",
    option_a: "Loop diuretics (e.g. furosemide)",
    option_b: "Carbonic anhydrase inhibitors",
    option_c: "Osmotic diuretics as first choice",
    option_d: "Potassium-sparing diuretics",
    option_e: "Thiazides as first choice",
    correct_answer: "A",
    explanation_a: "Loop diuretics are the most potent and are first-line for acute pulmonary oedema.",
    explanation_b: "Carbonic anhydrase inhibitors are weak diuretics, not first-line here.",
    explanation_c: "Osmotic diuretics are not the first choice for pulmonary oedema (and can worsen it acutely).",
    explanation_d: "Potassium-sparing diuretics are weak and not used for acute pulmonary oedema.",
    explanation_e: "Thiazides are moderate and not the first choice for acute pulmonary oedema.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Loop Diuretic Uses); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loop diuretics = most potent → treatment of choice for acute pulmonary oedema. IV furosemide also causes venodilation, reducing preload quickly. They remain effective even when GFR is low.",
  },
  {
    question: "A well-recognised set of adverse effects of loop diuretics such as furosemide includes:",
    case_study: "",
    option_a: "Hyperkalaemia and metabolic acidosis",
    option_b: "Hypokalaemia, metabolic alkalosis, and ototoxicity",
    option_c: "Weight gain and fluid overload",
    option_d: "Hyperglycaemia only",
    option_e: "No electrolyte disturbance",
    correct_answer: "B",
    explanation_a: "Loops cause hypokalaemia and alkalosis, not hyperkalaemia and acidosis.",
    explanation_b: "Loop diuretics classically cause hypokalaemia, metabolic alkalosis and (dose-related) ototoxicity.",
    explanation_c: "They cause fluid loss, not weight gain and overload.",
    explanation_d: "Hyperuricaemia can occur, but 'hyperglycaemia only' is incomplete and not the classic set.",
    explanation_e: "They cause significant electrolyte disturbance.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Loop Diuretic Toxicity); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loop diuretics → hypokalaemia + metabolic alkalosis + ototoxicity (among others). They also cause hypocalcaemia, hypomagnesaemia and hyperuricaemia (gout). Ototoxicity is worse when combined with aminoglycosides.",
  },
  {
    question: "Loop diuretics INCREASE urinary calcium excretion, which makes them useful in the emergency management of:",
    case_study: "",
    option_a: "Hypocalcaemia",
    option_b: "Osteoporosis prevention",
    option_c: "Hypercalcaemia",
    option_d: "Kidney stone prevention",
    option_e: "Low potassium",
    correct_answer: "C",
    explanation_a: "They worsen, not treat, hypocalcaemia.",
    explanation_b: "They increase calcium loss, so they do not prevent osteoporosis.",
    explanation_c: "By increasing calcium excretion, loop diuretics (with saline) help treat hypercalcaemia.",
    explanation_d: "Increasing urinary calcium tends to promote, not prevent, calcium stones.",
    explanation_e: "They cause, rather than treat, low potassium.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Calcium Handling); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loop diuretics increase calcium loss → used to treat hypercalcaemia. This is the opposite of thiazides, which decrease calcium excretion and are used for calcium stones.",
  },
  {
    question: "Thiazide diuretics (e.g. hydrochlorothiazide) act by inhibiting the Na⁺-Cl⁻ cotransporter in which segment of the nephron?",
    case_study: "",
    option_a: "The thick ascending limb",
    option_b: "The proximal tubule",
    option_c: "The collecting duct",
    option_d: "The distal convoluted tubule",
    option_e: "The descending limb of the loop of Henle",
    correct_answer: "D",
    explanation_a: "The thick ascending limb is the site of loop diuretics.",
    explanation_b: "The proximal tubule is the site of acetazolamide.",
    explanation_c: "The collecting duct is the site of potassium-sparing diuretics.",
    explanation_d: "Thiazides inhibit the Na⁺-Cl⁻ cotransporter in the distal convoluted tubule.",
    explanation_e: "The descending limb is a site of water (osmotic) handling, not the Na-Cl cotransporter.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Thiazides); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Thiazides act on the distal convoluted tubule via the Na-Cl (NCC) cotransporter. Thiazides decrease urinary calcium (hypocalciuria). They are less potent than loop diuretics but effective antihypertensives.",
  },
  {
    question: "Thiazide diuretics are widely used as a first-line treatment for:",
    case_study: "",
    option_a: "Acute pulmonary oedema as first choice",
    option_b: "Hypercalcaemia",
    option_c: "Severe dehydration",
    option_d: "Hyperkalaemia",
    option_e: "Hypertension",
    correct_answer: "E",
    explanation_a: "Loop diuretics, not thiazides, are first choice for acute pulmonary oedema.",
    explanation_b: "Thiazides cause mild hypercalcaemia; they do not treat hypercalcaemia.",
    explanation_c: "They promote fluid loss and are not a treatment for dehydration.",
    explanation_d: "They cause hypokalaemia, not treat hyperkalaemia.",
    explanation_e: "Thiazides are a first-line class for hypertension.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Thiazide Uses); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Thiazides are a first-line antihypertensive. They also help prevent calcium stones (hypocalciuria) and treat nephrogenic diabetes insipidus. They lower blood pressure partly by reducing peripheral vascular resistance over time.",
  },
  {
    question: "Unlike loop diuretics, thiazide diuretics DECREASE urinary calcium excretion. This property makes them useful in patients with:",
    case_study: "",
    option_a: "Recurrent calcium kidney stones (they reduce urinary calcium)",
    option_b: "Hypercalcaemia",
    option_c: "Severe hyperkalaemia",
    option_d: "Diabetes insipidus of pituitary origin only",
    option_e: "Gout",
    correct_answer: "A",
    explanation_a: "By reducing urinary calcium, thiazides help prevent recurrent calcium kidney stones.",
    explanation_b: "They cause mild hypercalcaemia, so they are not used to treat hypercalcaemia.",
    explanation_c: "They do not treat hyperkalaemia.",
    explanation_d: "They help nephrogenic diabetes insipidus, not pituitary (central) diabetes insipidus.",
    explanation_e: "They can worsen gout (hyperuricaemia), not treat it.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Thiazides and Calcium); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Thiazides retain calcium (hypocalciuria) → prevent recurrent calcium stones. This is the opposite of loop diuretics, which increase calcium loss. They may also help preserve bone density.",
  },
  {
    question: "The metabolic adverse effects of thiazide diuretics can be remembered as 'hyperGLUC'. Which set of disturbances does this represent?",
    case_study: "",
    option_a: "Low glucose, low lipids, low uric acid",
    option_b: "Hyperglycaemia, hyperlipidaemia, hyperuricaemia and hypercalcaemia (plus hypokalaemia)",
    option_c: "No metabolic effects",
    option_d: "Hyperkalaemia and metabolic acidosis",
    option_e: "Weight gain and oedema",
    correct_answer: "B",
    explanation_a: "These are the opposite of the actual effects.",
    explanation_b: "'HyperGLUC' = hyperGlycaemia, hyperLipidaemia, hyperUricaemia and hyperCalcaemia, with hypokalaemia.",
    explanation_c: "Thiazides do have metabolic effects.",
    explanation_d: "They cause hypokalaemia and alkalosis, not hyperkalaemia and acidosis.",
    explanation_e: "They cause fluid loss, not weight gain and oedema.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Thiazide Toxicity); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "HyperGLUC = Glucose, Lipids, Uric acid and Calcium all raised (K⁺ and Na⁺ lowered). Caution is needed in patients with diabetes and gout. Electrolytes should be monitored during thiazide therapy.",
  },
  {
    question: "Spironolactone is a potassium-sparing diuretic that acts in the collecting duct by:",
    case_study: "",
    option_a: "Blocking the Na-K-2Cl cotransporter",
    option_b: "Inhibiting carbonic anhydrase",
    option_c: "Competitively blocking the aldosterone (mineralocorticoid) receptor",
    option_d: "Blocking the Na-Cl cotransporter",
    option_e: "Osmotically holding water",
    correct_answer: "C",
    explanation_a: "Blocking Na-K-2Cl is the loop diuretic mechanism.",
    explanation_b: "Inhibiting carbonic anhydrase is acetazolamide's mechanism.",
    explanation_c: "Spironolactone competitively blocks the aldosterone (mineralocorticoid) receptor in the collecting duct.",
    explanation_d: "Blocking Na-Cl is the thiazide mechanism.",
    explanation_e: "Osmotically holding water is the osmotic diuretic mechanism.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Aldosterone Antagonists); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Spironolactone = aldosterone-receptor antagonist in the collecting duct. It reduces sodium reabsorption and potassium secretion (retaining potassium). It reduces mortality in heart failure and is used in hyperaldosteronism (Conn's) and cirrhotic ascites.",
  },
  {
    question: "A recognised side effect of spironolactone, due to its anti-androgenic activity, is:",
    case_study: "",
    option_a: "Hair loss",
    option_b: "Deep voice",
    option_c: "Weight loss",
    option_d: "Gynaecomastia (breast enlargement)",
    option_e: "Improved vision",
    correct_answer: "D",
    explanation_a: "Hair loss is not the characteristic effect.",
    explanation_b: "A deep voice is an androgenic effect, not an anti-androgenic one.",
    explanation_c: "Weight loss is not the recognised effect.",
    explanation_d: "Spironolactone's anti-androgenic action can cause gynaecomastia.",
    explanation_e: "It does not improve vision.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Spironolactone Adverse Effects); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Spironolactone → gynaecomastia (anti-androgenic effect). It can also cause impotence in men and menstrual irregularities in women. The more selective eplerenone causes less gynaecomastia.",
  },
  {
    question: "Amiloride and triamterene are potassium-sparing diuretics that, unlike spironolactone, act by directly:",
    case_study: "",
    option_a: "Blocking the aldosterone receptor",
    option_b: "Inhibiting the Na-K-2Cl cotransporter",
    option_c: "Inhibiting carbonic anhydrase",
    option_d: "Blocking the Na-Cl cotransporter",
    option_e: "Blocking the epithelial sodium channel (ENaC) in the collecting duct",
    correct_answer: "E",
    explanation_a: "Blocking the aldosterone receptor is spironolactone's mechanism.",
    explanation_b: "Inhibiting Na-K-2Cl is the loop diuretic mechanism.",
    explanation_c: "Inhibiting carbonic anhydrase is acetazolamide's mechanism.",
    explanation_d: "Blocking Na-Cl is the thiazide mechanism.",
    explanation_e: "Amiloride and triamterene directly block the epithelial sodium channel (ENaC) in the collecting duct.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (ENaC Blockers); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Amiloride/triamterene block ENaC directly in the collecting duct. They act independently of aldosterone, unlike spironolactone. They are often combined with thiazide/loop diuretics to offset hypokalaemia.",
  },
  {
    question: "The main dangerous side effect shared by all potassium-sparing diuretics (spironolactone, amiloride, triamterene) is:",
    case_study: "",
    option_a: "Hyperkalaemia",
    option_b: "Hypokalaemia",
    option_c: "Severe dehydration",
    option_d: "Metabolic acidosis is impossible",
    option_e: "Hyperglycaemia",
    correct_answer: "A",
    explanation_a: "Potassium-sparing diuretics retain potassium, so their main hazard is hyperkalaemia.",
    explanation_b: "They cause hyperkalaemia, not hypokalaemia (that is loops/thiazides).",
    explanation_c: "Severe dehydration is not their characteristic main danger.",
    explanation_d: "They can in fact cause a metabolic acidosis, so this statement is wrong.",
    explanation_e: "Hyperglycaemia is a thiazide effect, not the shared danger of potassium-sparing agents.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Potassium-Sparing Diuretics); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Potassium-sparing diuretics → risk of hyperkalaemia. The risk rises with renal impairment, ACE inhibitors/ARBs, potassium supplements or NSAIDs. Hyperkalaemia can cause dangerous cardiac arrhythmias, so potassium must be monitored.",
  },
  {
    question: "Antidiuretic hormone (ADH/vasopressin) reduces urine volume by acting on the collecting duct to:",
    case_study: "",
    option_a: "Increase sodium excretion",
    option_b: "Increase water reabsorption by inserting aquaporin channels (via V2 receptors)",
    option_c: "Block the Na-K-2Cl cotransporter",
    option_d: "Increase potassium loss",
    option_e: "Cause a water diuresis",
    correct_answer: "B",
    explanation_a: "ADH's primary renal action is water reabsorption, not sodium excretion.",
    explanation_b: "ADH acts on V2 receptors to insert aquaporin channels, increasing water reabsorption.",
    explanation_c: "ADH does not act by blocking the Na-K-2Cl cotransporter.",
    explanation_d: "Increasing potassium loss is not ADH's action.",
    explanation_e: "ADH reduces urine volume (antidiuresis), it does not cause a water diuresis.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Vasopressin); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "ADH → aquaporin-2 insertion in the collecting duct → water reabsorption. It concentrates the urine and conserves body water. ADH deficiency or resistance causes diabetes insipidus; excess causes SIADH.",
  },
  {
    question: "Desmopressin (a synthetic ADH analogue) is the treatment of choice for:",
    case_study: "",
    option_a: "Nephrogenic diabetes insipidus only",
    option_b: "SIADH",
    option_c: "Central (cranial) diabetes insipidus",
    option_d: "Simple dehydration",
    option_e: "Hypertension",
    correct_answer: "C",
    explanation_a: "Nephrogenic diabetes insipidus responds poorly, as the defect is renal resistance to ADH.",
    explanation_b: "SIADH involves excess ADH, so an ADH analogue would worsen it.",
    explanation_c: "Desmopressin replaces ADH and is the treatment of choice for central (cranial) diabetes insipidus.",
    explanation_d: "It is not the treatment for simple dehydration.",
    explanation_e: "It is not an antihypertensive.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Desmopressin); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Desmopressin replaces ADH in central diabetes insipidus. It is also used in nocturnal enuresis and some bleeding disorders (it releases von Willebrand factor). Nephrogenic diabetes insipidus does not respond, because the kidney is resistant to ADH.",
  },
  {
    question: "A newer class of drugs used in type 2 diabetes, the SGLT2 inhibitors (e.g. empagliflozin), produce glucose loss in the urine and a mild diuresis by acting on which part of the nephron?",
    case_study: "",
    option_a: "The collecting duct",
    option_b: "The thick ascending limb",
    option_c: "The distal convoluted tubule",
    option_d: "The proximal convoluted tubule",
    option_e: "The glomerulus",
    correct_answer: "D",
    explanation_a: "The collecting duct is the site of potassium-sparing diuretics and ADH.",
    explanation_b: "The thick ascending limb is the site of loop diuretics.",
    explanation_c: "The distal convoluted tubule is the site of thiazides.",
    explanation_d: "SGLT2 inhibitors block the sodium-glucose cotransporter-2 in the proximal convoluted tubule.",
    explanation_e: "The glomerulus filters blood but is not the SGLT2 site.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (SGLT2 Inhibitors); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "SGLT2 inhibitors act at the proximal tubule → glucosuria + mild osmotic diuresis. They also benefit heart failure and chronic kidney disease. Side effects include genital/urinary infections and volume depletion.",
  },
  {
    question: "Which of the following correctly matches a diuretic class with its main site of action in the nephron?",
    case_study: "",
    option_a: "Loop diuretics act on the collecting duct",
    option_b: "Thiazides act on the proximal tubule",
    option_c: "Acetazolamide acts on the loop of Henle",
    option_d: "Osmotic diuretics act on the aldosterone receptor",
    option_e: "Potassium-sparing diuretics act on the collecting duct",
    correct_answer: "E",
    explanation_a: "Loop diuretics act on the thick ascending limb, not the collecting duct.",
    explanation_b: "Thiazides act on the distal convoluted tubule, not the proximal tubule.",
    explanation_c: "Acetazolamide acts on the proximal tubule, not the loop of Henle.",
    explanation_d: "Osmotic diuretics act within the tubule lumen, not on the aldosterone receptor.",
    explanation_e: "Potassium-sparing diuretics act on the collecting duct.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology (Diuretic Sites); Lippincott Illustrated Reviews Pharmacology",
    is_fcps_pearl: true,
    fcps_pearl_content: "Potassium-sparing diuretics act on the collecting duct. Knowing the site predicts the effects and the electrolyte disturbances. Acetazolamide (proximal) → loop (thick ascending limb) → thiazide (distal convoluted tubule) → potassium-sparing (collecting duct).",
  },
];
