export const pharmacologyBlock1MCQs = [
  {
    question: "A drug given orally produces much lower blood levels than the same dose given intravenously. This reduced oral bioavailability is mainly due to:",
    case_study: "",
    option_a: "First-pass (presystemic) metabolism in the gut and liver",
    option_b: "Increased renal excretion",
    option_c: "Faster tissue distribution",
    option_d: "Higher plasma protein binding",
    option_e: "Slower absorption only",
    correct_answer: "A",
    explanation_a: "Orally absorbed drugs pass through the gut wall and liver before reaching the systemic circulation; first-pass metabolism there reduces the fraction that survives, lowering oral bioavailability.",
    explanation_b: "Renal excretion is similar whatever the route and is not the reason oral levels are lower.",
    explanation_c: "Distribution speed does not change total bioavailability.",
    explanation_d: "Protein binding affects free drug but not the bioavailable fraction itself.",
    explanation_e: "Slow absorption alters the rate, but first-pass metabolism is the main reason.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung Basic & Clinical Pharmacology; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Bioavailability is the fraction of an administered dose reaching the systemic circulation unchanged; it is 100% for the IV route. Low oral bioavailability is mainly due to first-pass metabolism. Drugs with high first-pass metabolism (e.g. GTN, propranolol, lidocaine) have low oral bioavailability.",
  },
  {
    question: "A patient with an acute angina attack is given glyceryl trinitrate (GTN) under the tongue rather than swallowed. The sublingual route is preferred because it:",
    case_study: "",
    option_a: "Is slower in onset",
    option_b: "Avoids first-pass hepatic metabolism",
    option_c: "Increases plasma protein binding",
    option_d: "Reduces the drug's potency",
    option_e: "Prolongs the elimination half-life",
    correct_answer: "B",
    explanation_a: "The sublingual route is actually fast in onset, which is why it is used in acute angina.",
    explanation_b: "Sublingual absorption drains into the systemic venous circulation directly, bypassing the portal system and so avoiding the heavy first-pass metabolism that would otherwise destroy GTN.",
    explanation_c: "It does not act by changing protein binding.",
    explanation_d: "It preserves, not reduces, the active drug reaching the circulation.",
    explanation_e: "It does not prolong the half-life.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Sublingual and rectal (partly) routes bypass first-pass metabolism, unlike the oral route. IV, sublingual and transdermal routes all avoid first-pass metabolism.",
  },
  {
    question: "A highly lipid-soluble drug leaves the plasma and concentrates in body tissues rather than staying in the blood. Such a drug will have:",
    case_study: "",
    option_a: "A small volume of distribution",
    option_b: "A zero volume of distribution",
    option_c: "A large volume of distribution",
    option_d: "No volume of distribution",
    option_e: "100% plasma protein binding",
    correct_answer: "C",
    explanation_a: "A small volume of distribution implies the drug stays largely in plasma/extracellular fluid, the opposite of this.",
    explanation_b: "A zero volume of distribution is physically meaningless.",
    explanation_c: "A large (high) apparent volume of distribution means most of the drug has left the plasma for the tissues, so the measured plasma concentration is low relative to the dose.",
    explanation_d: "Every drug has a calculable apparent volume of distribution.",
    explanation_e: "Heavy plasma protein binding tends to KEEP a drug in plasma, giving a SMALL volume of distribution.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Vd = dose ÷ plasma concentration; a very large Vd means extensive tissue distribution and usually little removal by dialysis. Lipid-soluble, tissue-bound drugs have a large volume of distribution. A large Vd makes a drug harder to remove by haemodialysis in overdose.",
  },
  {
    question: "A patient is started on a drug at a regular maintenance dose without a loading dose. Approximately how many half-lives are needed to reach steady-state plasma concentration?",
    case_study: "",
    option_a: "Half of one half-life",
    option_b: "1 half-life",
    option_c: "2 half-lives",
    option_d: "4–5 half-lives",
    option_e: "About 20 half-lives",
    correct_answer: "D",
    explanation_a: "Half a half-life gives only ~30% of steady state.",
    explanation_b: "One half-life gives only ~50% of steady state.",
    explanation_c: "Two half-lives give ~75%, still not steady state.",
    explanation_d: "Steady state (when the amount given equals the amount eliminated) is effectively reached after about 4–5 half-lives, regardless of the dose or interval.",
    explanation_e: "20 half-lives is far more than needed; the plateau is essentially reached by 4–5.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Steady state is reached in ~4–5 half-lives. The same ~4–5 half-lives rule applies to drug elimination – ~97% is cleared after 5 half-lives. A loading dose reaches the target concentration immediately, without waiting 4–5 half-lives.",
  },
  {
    question: "A critically ill patient needs a therapeutic drug concentration immediately rather than after several half-lives. The best way to achieve this rapidly is to give:",
    case_study: "",
    option_a: "A smaller maintenance dose",
    option_b: "The drug less frequently",
    option_c: "A drug with a longer half-life",
    option_d: "Only the usual maintenance dose",
    option_e: "A loading dose",
    correct_answer: "E",
    explanation_a: "A smaller maintenance dose reaches steady state even more slowly.",
    explanation_b: "Less frequent dosing slows the approach to therapeutic levels.",
    explanation_c: "Choosing a longer-half-life drug would make the rise to steady state slower, not faster.",
    explanation_d: "The maintenance dose alone still takes ~4–5 half-lives to plateau.",
    explanation_e: "A loading dose rapidly fills the volume of distribution to reach the target concentration at once; maintenance dosing then keeps it there.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Loading dose = target concentration × volume of distribution (it depends on Vd, not on clearance). A loading dose achieves a therapeutic level rapidly. Maintenance dose depends on clearance; loading dose depends on volume of distribution.",
  },
  {
    question: "A patient has phenytoin toxicity. Phenytoin – like ethanol and high-dose aspirin – is eliminated at a constant AMOUNT per unit time regardless of its concentration, because its metabolising enzymes are saturated. This pattern is called:",
    case_study: "",
    option_a: "Zero-order kinetics",
    option_b: "First-order kinetics",
    option_c: "Second-order kinetics",
    option_d: "Constant-fraction kinetics",
    option_e: "Linear first-order elimination",
    correct_answer: "A",
    explanation_a: "In zero-order (saturation) kinetics a fixed amount of drug is eliminated per unit time because the enzymes are working at maximum; small dose increases can then cause large rises in plasma level.",
    explanation_b: "First-order kinetics removes a constant FRACTION (not amount) per unit time.",
    explanation_c: "âSecond-orderâ is not a standard pharmacokinetic elimination order for these drugs.",
    explanation_d: "Constant-fraction elimination describes first-order, not zero-order, kinetics.",
    explanation_e: "Linear first-order elimination is the opposite of saturable zero-order kinetics.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Zero-order drugs (âPEAâ: Phenytoin, Ethanol, Aspirin at high dose) can show disproportionate, dangerous rises in level with small dose increases. Zero-order kinetics = constant amount eliminated per unit time (saturated enzymes). In zero-order kinetics the half-life is not constant; it lengthens as concentration rises.",
  },
  {
    question: "For most drugs at normal therapeutic doses, a constant FRACTION (percentage) of the drug present is eliminated per unit time. This is called:",
    case_study: "",
    option_a: "Zero-order kinetics",
    option_b: "First-order kinetics",
    option_c: "Constant-amount kinetics",
    option_d: "Saturation kinetics",
    option_e: "Capacity-limited kinetics",
    correct_answer: "B",
    explanation_a: "Zero-order kinetics eliminates a constant amount, not fraction.",
    explanation_b: "First-order kinetics means a constant proportion of drug is eliminated per unit time, giving a constant half-life; this applies to most drugs.",
    explanation_c: "âConstant-amountâ describes zero-order kinetics.",
    explanation_d: "Saturation kinetics is another name for zero-order kinetics.",
    explanation_e: "Capacity-limited kinetics is zero-order, the opposite of first-order.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "First-order kinetics = constant fraction eliminated per unit time (constant half-life). In first-order kinetics the half-life stays constant regardless of concentration. Most drugs follow first-order kinetics; a few saturate and become zero-order.",
  },
  {
    question: "A drug is metabolised in the liver by oxidation reactions carried out by the cytochrome P450 enzyme system. This is an example of which phase of drug metabolism?",
    case_study: "",
    option_a: "Phase II conjugation",
    option_b: "Renal excretion",
    option_c: "Phase I (oxidation, reduction, hydrolysis)",
    option_d: "Plasma protein binding",
    option_e: "Active tubular secretion",
    correct_answer: "C",
    explanation_a: "Phase II is conjugation (e.g. glucuronidation), which usually FOLLOWS phase I.",
    explanation_b: "Renal excretion is elimination, not metabolism.",
    explanation_c: "Phase I reactions (oxidation, reduction, hydrolysis), largely by cytochrome P450, introduce or expose a functional group, often producing a more polar (and sometimes active) metabolite.",
    explanation_d: "Plasma protein binding is a distribution phenomenon, not metabolism.",
    explanation_e: "Active tubular secretion is a renal excretory process.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Phase I = oxidation/reduction/hydrolysis (cytochrome P450). Phase I can create active or toxic metabolites; phase II usually inactivates and aids excretion. CYP3A4 is the most abundant hepatic P450 and metabolises the majority of drugs.",
  },
  {
    question: "After initial oxidation, a drug is joined (conjugated) with glucuronic acid to make it more water-soluble for excretion. This conjugation reaction is:",
    case_study: "",
    option_a: "Phase I metabolism",
    option_b: "Renal reabsorption",
    option_c: "First-pass absorption",
    option_d: "Phase II (conjugation) metabolism",
    option_e: "Active transport into cells",
    correct_answer: "D",
    explanation_a: "Phase I introduces/exposes functional groups; it usually precedes conjugation.",
    explanation_b: "Renal reabsorption returns drug to the blood, not a metabolic step.",
    explanation_c: "First-pass absorption is not a conjugation reaction.",
    explanation_d: "Phase II metabolism conjugates a drug or its phase I metabolite with groups such as glucuronate, sulfate, glutathione or acetate, greatly increasing water solubility for excretion.",
    explanation_e: "Active transport moves drug across membranes; it is not conjugation.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Phase II = conjugation – water-soluble metabolite for excretion. Glucuronidation, sulfation, acetylation and glutathione conjugation are the main phase II reactions. Conjugated metabolites are usually inactive and readily excreted in urine or bile.",
  },
  {
    question: "A woman taking the oral contraceptive pill is started on rifampicin for tuberculosis and later becomes pregnant. Rifampicin caused contraceptive failure because it:",
    case_study: "",
    option_a: "Inhibits liver enzymes",
    option_b: "Displaces the pill from plasma proteins",
    option_c: "Reduces renal excretion of the pill",
    option_d: "Increases absorption of the pill",
    option_e: "Induces hepatic enzymes, increasing metabolism of the pill",
    correct_answer: "E",
    explanation_a: "Rifampicin INDUCES, not inhibits, liver enzymes.",
    explanation_b: "Protein displacement is not its mechanism here.",
    explanation_c: "It does not act by reducing renal excretion.",
    explanation_d: "It does not increase absorption of the pill.",
    explanation_e: "Rifampicin is a potent inducer of hepatic cytochrome P450 enzymes; it speeds metabolism of the oestrogen/progestogen, lowering their levels and causing contraceptive failure.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Enzyme inducers – remember âCRAP-GPSâ (Carbamazepine, Rifampicin, Alcohol[chronic], Phenytoin, Griseofulvin, Phenobarbitone, Sulfonylureas/St Johnâs wort) – speed up metabolism of other drugs. Enzyme induction REDUCES the effect of drugs metabolised by that enzyme (e.g. OCP, warfarin).",
  },
  {
    question: "A patient stabilised on warfarin is given erythromycin for a chest infection, and his INR rises dangerously. Erythromycin increased the warfarin effect because it:",
    case_study: "",
    option_a: "Inhibits hepatic P450 enzymes, reducing warfarin metabolism",
    option_b: "Induces liver enzymes",
    option_c: "Increases warfarin excretion",
    option_d: "Reduces warfarin absorption",
    option_e: "Displaces warfarin onto albumin",
    correct_answer: "A",
    explanation_a: "Erythromycin (and clarithromycin) inhibits cytochrome P450, slowing warfarin metabolism so warfarin accumulates and the INR rises, risking bleeding.",
    explanation_b: "Enzyme INDUCTION would lower, not raise, the warfarin effect.",
    explanation_c: "Increasing excretion would lower the effect, not raise it.",
    explanation_d: "Reduced absorption would lower warfarin levels.",
    explanation_e: "Erythromycin does not raise the INR by protein displacement.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Enzyme inhibitors – remember âGO-DEVICESâ type lists (e.g. Grapefruit juice, Omeprazole/cimetidine, Disulfiram, Erythromycin, Valproate, Isoniazid, Ciprofloxacin, Ketoconazole, Sulfonamides) – raise levels of co-administered drugs. Enzyme inhibition INCREASES the effect/toxicity of drugs metabolised by that enzyme.",
  },
  {
    question: "In a study, a competitive (reversible) antagonist is given together with an agonist. On the agonist's dose–response curve, the competitive antagonist:",
    case_study: "",
    option_a: "Shifts the curve to the left",
    option_b: "Shifts the agonist curve to the right and is surmountable by more agonist",
    option_c: "Reduces the maximal response and is insurmountable",
    option_d: "Has no effect on the curve",
    option_e: "Increases the agonist's potency",
    correct_answer: "B",
    explanation_a: "A leftward shift would mean increased potency, the opposite effect.",
    explanation_b: "A competitive antagonist shifts the agonist dose–response curve to the right (reducing apparent potency) but the maximal response can still be reached with enough agonist – it is surmountable.",
    explanation_c: "Reduced maximal response that cannot be overcome describes a NON-competitive (irreversible) antagonist.",
    explanation_d: "A competitive antagonist clearly alters the curve.",
    explanation_e: "It decreases, not increases, apparent agonist potency.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Competitive antagonism is overcome by increasing the agonist dose; non-competitive antagonism is not. Competitive antagonist – rightward shift, surmountable, maximal response preserved. Non-competitive/irreversible antagonists lower the maximal response (Emax) and are insurmountable.",
  },
  {
    question: "A drug binds its receptor but produces only a submaximal effect even when all the receptors are occupied. This drug is best described as a:",
    case_study: "",
    option_a: "Full agonist",
    option_b: "Competitive antagonist",
    option_c: "Partial agonist",
    option_d: "Irreversible antagonist",
    option_e: "Inverse agonist",
    correct_answer: "C",
    explanation_a: "A full agonist produces the maximal response.",
    explanation_b: "A competitive antagonist produces no response of its own.",
    explanation_c: "A partial agonist has affinity but only submaximal efficacy, so even at full receptor occupancy it cannot produce the maximal response of a full agonist.",
    explanation_d: "An irreversible antagonist also produces no response and lowers Emax for agonists.",
    explanation_e: "An inverse agonist produces an effect opposite to the agonist (reduces basal/constitutive activity).",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Partial agonist = submaximal effect even at full receptor occupancy. In the presence of a full agonist, a partial agonist can behave as a partial ANTAGONIST by occupying receptors with lower efficacy. Examples include buprenorphine (opioid) and pindolol (β-blocker with partial agonist activity).",
  },
  {
    question: "Drug A produces its effect at a much lower dose than Drug B, but both eventually reach the same maximal effect. Compared with Drug B, Drug A has:",
    case_study: "",
    option_a: "Greater efficacy",
    option_b: "Lower efficacy",
    option_c: "A greater maximal effect",
    option_d: "Greater potency (with equal efficacy)",
    option_e: "A higher therapeutic index",
    correct_answer: "D",
    explanation_a: "Equal maximal effect means equal efficacy, not greater efficacy for A.",
    explanation_b: "Drug A does not have lower efficacy; its maximum equals Drug B's.",
    explanation_c: "The maximal effect is the same for both.",
    explanation_d: "Needing a lower dose for the same effect means greater POTENCY; reaching the same maximal effect means the two drugs have equal EFFICACY.",
    explanation_e: "Potency says nothing directly about the therapeutic index.",
    difficulty: "Hard",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Potency (position on the dose axis, EC50) and efficacy (height of the curve, Emax) are independent properties. Lower effective dose = greater potency; same maximal effect = equal efficacy. A more potent drug is not necessarily clinically better; efficacy and safety matter more.",
  },
  {
    question: "A patient on digoxin requires regular blood-level monitoring because the dose that causes toxicity is very close to the therapeutic dose. This means digoxin has:",
    case_study: "",
    option_a: "A wide therapeutic index",
    option_b: "High potency",
    option_c: "Low efficacy",
    option_d: "Zero-order kinetics",
    option_e: "A narrow therapeutic index",
    correct_answer: "E",
    explanation_a: "A wide therapeutic index would mean a large safety margin and little need for monitoring.",
    explanation_b: "Potency refers to dose for effect, not the safety margin.",
    explanation_c: "Efficacy refers to maximal effect, not the safety margin.",
    explanation_d: "Zero-order kinetics is an elimination pattern, not the definition of the safety margin.",
    explanation_e: "A narrow therapeutic index means a small margin between effective and toxic doses, so drugs like digoxin need careful dosing and therapeutic drug monitoring.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Narrow therapeutic index = small gap between effective and toxic dose (monitor levels). Narrow-therapeutic-index drugs include digoxin, warfarin, lithium, phenytoin, theophylline and aminoglycosides – all need monitoring. Therapeutic index = toxic dose (TD50/LD50) ÷ effective dose (ED50); higher is safer.",
  },
  {
    question: "Insulin produces its cellular effects by binding to a cell-surface receptor that has intrinsic enzyme activity in its cytoplasmic tail. The insulin receptor is a:",
    case_study: "",
    option_a: "Receptor tyrosine kinase",
    option_b: "G-protein-coupled receptor",
    option_c: "Ligand-gated ion channel",
    option_d: "Intracellular (nuclear) receptor",
    option_e: "Voltage-gated ion channel",
    correct_answer: "A",
    explanation_a: "The insulin receptor is a receptor tyrosine kinase; insulin binding activates autophosphorylation and a downstream phosphorylation cascade.",
    explanation_b: "G-protein-coupled receptors (e.g. β-adrenergic) act via G proteins and second messengers, not intrinsic kinase activity.",
    explanation_c: "Ligand-gated ion channels (e.g. nicotinic receptor) open a pore on ligand binding.",
    explanation_d: "Intracellular/nuclear receptors bind lipid-soluble hormones (e.g. steroids), not insulin.",
    explanation_e: "Voltage-gated channels respond to membrane potential, not hormone binding.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Other receptor tyrosine kinases include those for many growth factors (e.g. EGF). Four main receptor types: ligand-gated channels, GPCRs, kinase-linked receptors and nuclear receptors.",
  },
  {
    question: "A lipid-soluble steroid drug crosses the cell membrane and binds a receptor that then alters gene transcription, producing a slow, prolonged effect. This receptor is:",
    case_study: "",
    option_a: "A G-protein-coupled receptor",
    option_b: "An intracellular (nuclear) receptor",
    option_c: "A ligand-gated ion channel",
    option_d: "A receptor tyrosine kinase",
    option_e: "A cell-surface enzyme",
    correct_answer: "B",
    explanation_a: "GPCRs are cell-surface receptors giving rapid second-messenger responses.",
    explanation_b: "Lipid-soluble steroids cross the membrane and bind intracellular (nuclear) receptors that act as transcription factors, changing gene expression – hence a delayed but lasting effect.",
    explanation_c: "Ligand-gated channels give very fast (millisecond) ionic responses at the surface.",
    explanation_d: "Receptor tyrosine kinases are cell-surface receptors (e.g. for insulin).",
    explanation_e: "A cell-surface enzyme acts at the membrane, not via gene transcription.",
    difficulty: "Moderate",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Nuclear-receptor (steroid, thyroid hormone, vitamin D, retinoid) effects are slow in onset but long-lasting because they change protein synthesis. Steroids act on intracellular (nuclear) receptors that regulate gene transcription. Lipid-soluble signals (steroids, thyroxine, vitamin D, retinoids) use intracellular receptors.",
  },
  {
    question: "A drug binds to a receptor (it has affinity) and activates it to produce a response (it has efficacy). This drug is called:",
    case_study: "",
    option_a: "An antagonist",
    option_b: "A partial agonist",
    option_c: "An agonist",
    option_d: "An inverse agonist",
    option_e: "A competitive blocker",
    correct_answer: "C",
    explanation_a: "An antagonist has affinity but no efficacy – it binds without activating.",
    explanation_b: "A partial agonist activates only submaximally.",
    explanation_c: "An agonist has both affinity (binds) and efficacy (activates the receptor to produce a response).",
    explanation_d: "An inverse agonist produces the opposite effect, reducing basal activity.",
    explanation_e: "A competitive blocker is a type of antagonist, with no activating effect.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Affinity is the tendency to bind; efficacy (intrinsic activity) is the ability to activate the receptor once bound. Agonist = affinity + efficacy (binds and activates). An antagonist has affinity but zero efficacy.",
  },
  {
    question: "A drug is administered by the intravenous route. Its bioavailability is:",
    case_study: "",
    option_a: "Less than 50%",
    option_b: "Reduced by first-pass metabolism",
    option_c: "Variable and unpredictable",
    option_d: "100% (complete)",
    option_e: "Zero",
    correct_answer: "D",
    explanation_a: "IV bioavailability is complete, not reduced.",
    explanation_b: "The IV route bypasses first-pass metabolism entirely.",
    explanation_c: "IV bioavailability is fixed at 100%, not variable.",
    explanation_d: "By definition, an intravenous drug enters the systemic circulation directly and completely, so its bioavailability is 100% (the reference standard).",
    explanation_e: "Zero bioavailability would mean no drug reaches the circulation, which is untrue for IV.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "IV route = 100% bioavailability. Oral bioavailability is expressed relative to the IV dose (which is taken as 100%). The IV route gives the fastest onset and the most predictable blood levels.",
  },
  {
    question: "A drug is eliminated almost entirely unchanged by the kidneys. In a patient with significant renal failure, the most appropriate action is to:",
    case_study: "",
    option_a: "Increase the dose",
    option_b: "Give it more frequently",
    option_c: "Make no change at all",
    option_d: "Stop all of the patient's other drugs",
    option_e: "Reduce the dose or lengthen the dosing interval",
    correct_answer: "E",
    explanation_a: "Increasing the dose would worsen accumulation and toxicity.",
    explanation_b: "More frequent dosing would also cause accumulation.",
    explanation_c: "Ignoring reduced clearance risks toxic drug levels.",
    explanation_d: "Stopping unrelated drugs is not the specific, appropriate adjustment here.",
    explanation_e: "If the kidney is the main route of elimination, renal failure reduces clearance and the drug accumulates, so the dose should be reduced or the interval lengthened to avoid toxicity.",
    difficulty: "Easy",
    subject: "Pharmacology",
    references: "Katzung; Lippincott Pharmacology; Rang & Dale",
    is_fcps_pearl: true,
    fcps_pearl_content: "Renally cleared drugs (e.g. aminoglycosides, digoxin, many others) need dose adjustment in renal impairment, often guided by creatinine clearance/eGFR. Renally eliminated drugs need dose reduction (or interval lengthening) in renal failure. Hepatically cleared drugs may instead need adjustment in liver failure.",
  },
];
